export const baseTemplateData = {
  "Next Of Kin": {
    fields: [
      {
        unique: false,
        options: [],
        required: true,
        fieldName: "nok_name",
        fieldType: "TextField",
        fieldTitle: "Name",
        primaryKey: null,
        placeHolder: "Full name",
      },
      {
        unique: false,
        options: [],
        required: true,
        fieldName: "nok_phone",
        fieldType: "IntegerField",
        fieldTitle: "Phone",
        primaryKey: null,
        placeHolder: "Phone number",
      },
      {
        unique: false,
        options: [
          "Brother",
          "Sister",
          "Uncle",
          "Aunt",
          "Son",
          "Daughter",
          "Wife",
          "Husband",
          "Mother",
          "Father",
          "Cousin",
          "Nephew",
          "Niece",
          "Others",
        ],
        required: true,
        fieldName: "nok_relationship",
        fieldType: "SelectField",
        fieldTitle: "Relationship",
        primaryKey: null,
        placeHolder: "What's their relation to you?",
      },
      {
        unique: false,
        options: [],
        required: true,
        fieldName: "nok_address",
        fieldType: "TextField",
        fieldTitle: "Address",
        primaryKey: null,
        placeHolder: "Residential Address",
      },
      {
        unique: false,
        options: [],
        required: true,
        fieldName: "nok_email_address",
        fieldType: "EmailField",
        fieldTitle: "Email Address",
        primaryKey: null,
        placeHolder: "Email Address",
      },
    ],
    sectionId: 2,
    description: "Setup your Next of Kin Information",
    sectionName: "Next Of Kin",
  },
  Contribution: {
    fields: [],
    sectionId: 3,
    description: "Setup your Monthly Contribution",
    sectionName: "Contribution",
  },
  "Bank Information": {
    fields: [
      {
        unique: false,
        options: [],
        required: true,
        fieldName: "bank_name",
        fieldType: "TextField",
        fieldTitle: "Bank Name",
        primaryKey: null,
        placeHolder: "Bank Name",
      },
      {
        unique: false,
        options: [],
        required: true,
        fieldName: "account_number",
        fieldType: "IntegerField",
        fieldTitle: "Account Number",
        primaryKey: null,
        placeHolder: "Account Number",
      },
      {
        unique: false,
        options: [],
        required: true,
        fieldName: "account_name",
        fieldType: "TextField",
        fieldTitle: "Account Name",
        primaryKey: null,
        placeHolder: "Account Name",
      },
    ],
    sectionId: 4,
    description: "Setup your Bank Information",
    sectionName: "Bank Information",
  },
  "Personal Details": {
    fields: [
      {
        unique: false,
        options: [],
        required: true,
        fieldName: "first_name",
        fieldType: "TextField",
        fieldTitle: "First Name",
        primaryKey: null,
        placeHolder: "First Name",
      },
      {
        unique: false,
        options: [],
        required: true,
        fieldName: "middle_name",
        fieldType: "TextField",
        fieldTitle: "Middle Name",
        primaryKey: null,
        placeHolder: "Middle Name",
      },
      {
        unique: false,
        options: [],
        required: true,
        fieldName: "last_name",
        fieldType: "TextField",
        fieldTitle: "Last Name",
        primaryKey: null,
        placeHolder: "Last Name",
      },
      {
        unique: false,
        options: [],
        required: true,
        fieldName: "image",
        fieldType: "ImageField",
        fieldTitle: "Profile Picture",
        primaryKey: null,
        placeHolder: "Image: jpeg, png, jpg (2mb MAX)",
      },
      {
        unique: false,
        options: [
          "Married",
          "Single",
          "Seperated",
          "Divorced",
          "Complicated",
          "Engaged",
        ],
        required: true,
        fieldName: "marital_status",
        fieldType: "SelectField",
        fieldTitle: "Marital Status",
        primaryKey: null,
        placeHolder: "Marital Status",
      },
      {
        unique: false,
        options: [],
        required: true,
        fieldName: "date_of_birth",
        fieldType: "DateField",
        fieldTitle: "Date Of Birth",
        primaryKey: null,
        placeHolder: "Date Of Birth",
      },
      {
        unique: false,
        options: [
          "Abia",
          "Adamawa",
          "Akwa Ibom",
          "Anambra",
          "Bauchi",
          "Bayelsa",
          "Benue",
          "Borno",
          "Cross River",
          "Delta",
          "Ebonyi",
          "Edo",
          "Ekiti",
          "Federal Capital Territory",
          "Enugu",
          "Gombe",
          "Imo",
          "Jigawa",
          "Kaduna",
          "Kano",
          "Katsina",
          "Kebbi",
          "Kogi",
          "Kwara",
          "Lagos",
          "Nasarawa",
          "Niger",
          "Ogun",
          "Ondo",
          "Osun",
          "Oyo",
          "Plateau",
          "Rivers",
          "Sokoto",
          "Taraba",
          "Yobe",
          "Zamfara",
        ],
        required: true,
        fieldName: "state_of_origin",
        fieldType: "SelectField",
        fieldTitle: "State Of Origin",
        primaryKey: null,
        placeHolder: "State Of Origin",
      },
      {
        unique: true,
        options: [],
        required: true,
        fieldName: "phone_number",
        fieldType: "IntegerField",
        fieldTitle: "Phone Number",
        primaryKey: null,
        placeHolder: "Phone Number",
      },
      {
        unique: true,
        options: [],
        required: true,
        fieldName: "email_address",
        fieldType: "EmailField",
        fieldTitle: "Email Address",
        primaryKey: null,
        placeHolder: "Email Address",
      },
    ],
    sectionId: 1,
    description: "Setup your Personal Information",
    sectionName: "Personal Details",
  },
};
